---
# Instalação de pacotes iniciais necessários ao ambiente
- hosts: all
  become: true
  tasks:
  - name: Install necessary packages
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
      - net-tools
      - make
      - build-essential
      - gcc
      - g++
      - cmake
      - libsctp-dev 
      - lksctp-tools
      - iproute2


  # Instalação do Gtp5G para funcionamento da UPF
  # Foi necessário instalar o pacote linux-headers pois não havia o diretório build em /lib/modules/<kernel_versionL
  - name: Gtp5G Instalation
    shell: 
      cmd: |
        sudo apt install -y linux-headers-$(uname -r)
        git clone https://github.com/free5gc/gtp5g.git && cd gtp5g
        make clean && make
        sudo make install

  # Instalação do ContainerD
  - name: Install containerd
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - containerd

# Removendo Swap para iniciar o Kubelet
  - name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none

  - name: Disable swap
    command: swapoff -a
    when: ansible_swaptotal_mb > 0

# Instalando Kubelet, Kubeadm e Kubectl
  - name: Add an apt signing key for Kubernetes
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: Adding apt repository for Kubernetes
    apt_repository:
      repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: kubernetes.list

  - name: Install Kubernetes binaries
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
        - kubelet=1.23.0-00
        - kubeadm=1.23.0-00
        - kubectl=1.23.0-00

# Configuração do ContainerD
  - name: Configura containerd
    blockinfile:
      create: true
      path: /etc/modules-load.d/containerd.conf
      block: |
        overlay
        br_netfilter

  - name: Enable kernel modules
    shell: |
      modprobe overlay
      modprobe br_netfilter
  
  - name: Configure IP forwarding and iptables
    blockinfile:
      create: true
      path: /etc/sysctl.conf
      block: |
        net.bridge.bridge-nf-call-iptables = 1
        net.ipv4.ip_forward = 1
  
  - name: Persist changes
    command: sysctl -p

  - name: Get IP eth1 addr
    shell: ifconfig eth1 | grep 'inet' | cut -d{{':'}} -f2 | awk '{ print $2 }'
    register: output

  - name: Configure Kubelet
    lineinfile:
      path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
      line: Environment="KUBELET_EXTRA_ARGS=--node-ip={{ output.stdout }}"

  - name: Copy the join command to server location
    copy: src=join-command dest=/tmp/join-command.sh mode=0777

  - name: Join the node to cluster
    command: sh /tmp/join-command.sh

 # Criação do diretório para receber o Volume Persistente
  - name: Create Volume Directory
    file: 
      path: /home/vagrant/kubedata
      state: directory 